<a href="https://colab.research.google.com/github/arushikhangar/Session-15/blob/main/DataExploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files

uploaded = files.upload()

Saving netflix_dataset.csv to netflix_dataset.csv

In [5]:
df = pd.read_csv("/content/netflix_dataset.csv")

In [6]:
df

,show_id,title,type,release_year,genre,country,rating,duration_min,views_millions
0,s0001,Netflix Title 1,Movie,2010,Documentary,India,6.1,77,184.4
1,s0002,Netflix Title 2,Movie,2023,Drama,USA,5.4,89,126.8
2,s0003,Netflix Title 3,Movie,2016,Documentary,Spain,8.2,113,55.9
3,s0004,Netflix Title 4,TV Show,2010,Romance,Japan,5.7,114,85.7
4,s0005,Netflix Title 5,Movie,2016,Romance,India,5.5,108,25.1
...,...,...,...,...,...,...,...,...,...
95,s0096,Netflix Title 96,TV Show,2010,Romance,Canada,8.7,73,108.9
96,s0097,Netflix Title 97,TV Show,2024,Documentary,UK,7.0,153,130.9
97,s0098,Netflix Title 98,TV Show,2025,Thriller,Canada,8.7,135,67.8
98,s0099,Netflix Title 99,Movie,2012,Action,Canada,6.1,119,142.9
99,s0100,Netflix Title 100,TV Show,2020,Drama,Canada,8.8,83,122.4

In [7]:
df.head()

,show_id,title,type,release_year,genre,country,rating,duration_min,views_millions
0,s0001,Netflix Title 1,Movie,2010,Documentary,India,6.1,77,184.4
1,s0002,Netflix Title 2,Movie,2023,Drama,USA,5.4,89,126.8
2,s0003,Netflix Title 3,Movie,2016,Documentary,Spain,8.2,113,55.9
3,s0004,Netflix Title 4,TV Show,2010,Romance,Japan,5.7,114,85.7
4,s0005,Netflix Title 5,Movie,2016,Romance,India,5.5,108,25.1

In [8]:
df.tail()

,show_id,title,type,release_year,genre,country,rating,duration_min,views_millions
95,s0096,Netflix Title 96,TV Show,2010,Romance,Canada,8.7,73,108.9
96,s0097,Netflix Title 97,TV Show,2024,Documentary,UK,7.0,153,130.9
97,s0098,Netflix Title 98,TV Show,2025,Thriller,Canada,8.7,135,67.8
98,s0099,Netflix Title 99,Movie,2012,Action,Canada,6.1,119,142.9
99,s0100,Netflix Title 100,TV Show,2020,Drama,Canada,8.8,83,122.4

In [9]:
df.shape

(100, 9)

In [10]:
df.columns

Index(['show_id', 'title', 'type', 'release_year', 'genre', 'country',
       'rating', 'duration_min', 'views_millions'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         100 non-null    object
 1   title           100 non-null    object
 2   type            100 non-null    object
 3   release_year    100 non-null    int64
 4   genre           100 non-null    object
 5   country         100 non-null    object
 6   rating          100 non-null    float64
 7   duration_min    100 non-null    int64
 8   views_millions  100 non-null    float64
dtypes: float64(2), int64(2), object(5)
memory usage: 7.2+ KB

In [13]:
df.describe()

       release_year      rating  duration_min  views_millions
count    100.000000  100.000000    100.000000      100.000000
mean    2017.250000    7.212000    118.120000      128.775000
std        4.515685    1.285842     33.573462       73.078645
min     2010.000000    5.000000     62.000000        2.400000
25%     2013.000000    6.075000     89.000000       68.550000
50%     2017.500000    7.100000    116.000000      129.150000
75%     2021.000000    8.325000    145.250000      189.825000
max     2025.000000    9.500000    180.000000      249.600000

In [14]:
df.dtypes

show_id            object
title              object
type               object
release_year        int64
genre              object
country            object
rating            float64
duration_min        int64
views_millions    float64
dtype: object

In [15]:
df.isnull().sum()

show_id           0
title             0
type              0
release_year      0
genre             0
country           0
rating            0
duration_min      0
views_millions    0
dtype: int64

In [17]:
df.nunique()

show_id           100
title             100
type                2
release_year       16
genre               7
country             7
rating             41
duration_min       61
views_millions     97
dtype: int64

In [19]:
df.sample(5)

,show_id,title,type,release_year,genre,country,rating,duration_min,views_millions
46,s0047,Netflix Title 47,Movie,2017,Action,India,5.7,166,136.3
35,s0036,Netflix Title 36,Movie,2012,Romance,Japan,6.1,112,121.9
12,s0013,Netflix Title 13,TV Show,2022,Action,USA,5.9,180,142.2
23,s0024,Netflix Title 24,TV Show,2017,Drama,UK,9.0,70,22.3
71,s0072,Netflix Title 72,TV Show,2012,Thriller,Canada,9.0,133,49.4

In [20]:
df.value_counts()

show_id  title              type     release_year  genre        country  rating  duration_min  views_millions
s0001    Netflix Title 1    Movie    2010          Documentary  India    6.1     77            184.4             1
s0002    Netflix Title 2    Movie    2023          Drama        USA      5.4     89            126.8             1
s0003    Netflix Title 3    Movie    2016          Documentary  Spain    8.2     113           55.9              1
s0004    Netflix Title 4    TV Show  2010          Romance      Japan    5.7     114           85.7              1
s0005    Netflix Title 5    Movie    2016          Romance      India    5.5     108           25.1              1
                                                                                                                ..
s0096    Netflix Title 96   TV Show  2010          Romance      Canada   8.7     73            108.9             1
s0097    Netflix Title 97   TV Show  2024          Documentary  UK       7.0     153           130.9             1
s0098    Netflix Title 98   TV Show  2025          Thriller     Canada   8.7     135           67.8              1
s0099    Netflix Title 99   Movie    2012          Action       Canada   6.1     119           142.9             1
s0100    Netflix Title 100  TV Show  2020          Drama        Canada   8.8     83            122.4             1
Name: count, Length: 100, dtype: int64